### ISSUE TITLE
How to instantiate objects into a template

### ISSUE THREAD

**Issue by adawolfs** [openshift/openshift-restclient-python#149]
Hello, I'm trying to instantiate a template into my cluster. I've found that there is a method called **create_namespaced_template_instance** but it only creates a resource "templateinstance" but doesn't create the objects into it aka pods, services, configmaps, etc... the status node has no conditions, can you help me with this?

**Comment by djzager** [comment]
I've never tried creating templates with the generated client. However, in the time since this question was originally asked, we have moved on to a dynamic client that makes requests more directly to the openshift/k8s API Server. I would recommend having a look at the https://github.com/openshift/openshift-restclient-python#dynamic-client-usage and see if that meets your needs. As far as instruction on how to use the API to create a template...I don't believe we have the required resources to help with that at this time.
