### ISSUE TITLE
Mismatch between OpenShift API spec and client APIs breaks SecurityContextConstraints

### ISSUE THREAD

**Issue by ceridwen** [openshift/openshift-restclient-python#170]
When you query the OpenShift API server, it claims that the SecurityContextConstraints resource is available on the `CoreV1Api` object.

```
>>> {r.kind for r in kubernetes.client.apis.core_v1_api.CoreV1Api().get_api_resources().resources}
{'Event', 'Scale', 'Service', 'ConfigMap', 'Eviction', 'SecurityContextConstraints', 'Namespace', 'Node', 'PodTemplate', 'Binding', 'ComponentStatus', 'PersistentVolume', 'LimitRange', 'PersistentVolumeClaim', 'ResourceQuota', 'Secret', 'Endpoints', 'ServiceAccount', 'ReplicationController', 'Pod'}
```

This is true for the OpenShift API server itself, since you can post a REST request against `/api/v1/securitycontextconstraints` and get something back.  It is *not* true, of course, for this client, because `CoreV1API` is a Kubernetes client class that doesn't know about OpenShift resources.  I've been discovering APIs by looking at the return values of `get_api_resources()` and other methods that ultimately depend on the API server but don't reflect what methods are available on the clients or where they're available.

Similarly, the [documentation](https://github.com/openshift/openshift-restclient-python/tree/master/openshift) shows the security_context_constraints methods on the `CoreV1Api` object, but the [links are dead](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/docs/CoreV1Api.md#create_security_context_constraints).

**Comment by djzager** [comment]
Yeah. This, unfortunately, is not unique. If you have a look at the script we use to generate the openshift client (https://github.com/openshift/openshift-restclient-python/blob/master/scripts/update-client.sh#L97) you'll see a couple of the others that we have come across. This is a class of issue where the generated client is actually too strict when compared to the k8s/openshift api server.

I would encourage you to use the dynamic client, mentioned here (https://github.com/openshift/openshift-restclient-python/#dynamic-client-usage) and see if that solves your problem. Since the dynamic client talks directly to the api server, I expect it will.
