### ISSUE TITLE
ResourceNotUniqueError on resources.get(api_version='v1', kind='DeploymentConfig')

### ISSUE THREAD

**Issue by FlorianFusseder** [openshift/openshift-restclient-python#284]
If i want to create a simple get with:
`dyn_client.resources.get(api_version='v1', kind='DeploymentConfig')`
 for a DeploymentConfig, ill get the following exception:

`  File "C:\Projekte\openshift-scripts\venv\lib\site-packages\openshift\dynamic\client.py", line 639, in get
    raise ResourceNotUniqueError('Multiple matches found for {}: {}'.format(kwargs, results))
openshift.dynamic.exceptions.ResourceNotUniqueError: Multiple matches found for {'api_version': 'v1', 'kind': 'DeploymentConfig'}: [<Resource(v1/deploymentconfigs)>, <Resource(v1/generatedeploymentconfigs)>]`

Shouldn't this be unique? It is a standard resource? How to i get the resource <Resource(v1/deploymentconfigs)>?

**Comment by willthames** [comment]
This is very similar to https://github.com/ansible/ansible/issues/55221

Only seems to be a problem for very old openshifts (3.6 or older), there is a workaround in the above issue.

@fabianvf do you any more thoughts on this one?

**Comment by cben** [comment]
There is also a similar collision between `/templates` and `/processedtemplates`, that still exists in openshift (3.11 and 4.1.0-rc.3): https://github.com/openshift/origin/issues/21668.
Can you check if you see similar issue with that?

FWIW in kubeclient (a ruby lib that's also a dynamic discovery-driven client),
I had similar issues: https://github.com/abonas/kubeclient/issues/376#issuecomment-447635128
and ended up simply blacklisting `processedtemplates`: https://github.com/abonas/kubeclient/pull/378
Unless you do want `oc process` like functionality too?  In kubeclient we had a special method to do it (https://github.com/abonas/kubeclient/pull/183).

I'm not sure what `generatedeploymentconfigs` did in the past but I suspect it was a similar POST-only arrangement to `processedtemplates`?  Or maybe it did nothing — 3.6.0 discovery says `"verbs": []`?  :man_shrugging: 
I didn't blacklist `generatedeploymentconfigs` because in kubeclient it didn't collide due to technicality in method names, but I think you can safely blacklist it too in openshift-restclient-python.

- There is also `ReplicationControllerDummy` for extensions/v1beta1/replicationcontrollers but that's separate api group, not same kind of collision, silly but harmless :smile_cat:?

P.S. https://github.com/cben/kubernetes-discovery-samples may come in handy for checking what discovery info looks like in different versions.
