### ISSUE TITLE
matches.extend(self.__search([key] + parts[1:], resources)) TypeError: 'Resource' object is not iterable

### ISSUE THREAD

**Issue by lucastheisen** [openshift/openshift-restclient-python#286]
[This line](https://github.com/openshift/openshift-restclient-python/blob/v0.8.7/openshift/dynamic/client.py#L679) allows for a recursive call to return a _non-iterable_ value which causes `extend` to throw this error. 

_I noticed that the latest code completely changes, but given that it is still tagged as alpha, and a minor version bump, i thought you might want to know...  We pegged our pip install to 0.8.6, so feel free to close and focus on 0.9_

**Comment by fabianvf** [comment]
Yeah this was due to sloppy change management on my part. Basically the client creates a cache of discovered resources, and in version 0.8.7 we slightly changed the structure of that cache, but since I didn't pin the cache to a specific version of the client loading an older cache causes this error. In order to work around this you can `rm ${TMPDIR}/osrcp-*.json`, this should get the client working again. I'll cut a release today that pins the cache to a specific library version too.

**Comment by fabianvf** [comment]
https://github.com/openshift/openshift-restclient-python/releases/tag/v0.8.8

**Comment by fabianvf** [comment]
@lucastheisen does this work for you with 0.8.8?

**Comment by lucastheisen** [comment]
Sorry, been out, havn't had a chance to test.  We reverted to the previous _working_ version prior to your response.  I will give this a try as soon as I can (might be another 2 weeks before i get to it), but feel free to close at any time.

**Comment by lucastheisen** [comment]
@fabianvf , sorry for the delay...  Finally updated to 0.8.8 today, no errors.  Thanks for the fix.
